spring.application.name=Library_User
server.port=8081
spring.data.mongodb.database=Library_User
spring.data.mongodb.uri=mongodb+srv://sachintha2001lakshan_db_use:e6QcbAm8T0L1IfJu@libraryuser.e9qzatj.mongodb.net/